version: "3.8"

services:
  app:
    build: .
    restart: always
    container_name: rumble
    image: rumble:latest
    volumes:
      - static-data:/app/staticfiles
      - media-data:/app/staticfiles
    command: >
      sh -c "python manage.py makemigrations mysite
             python manage.py migrate --noinput && 
             python manage.py collectstatic --noinput &&
             gunicorn setup.wsgi --bind 0.0.0.0:8000 --workers 1 --timeout 30"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=5432
      - MAP_API_KEY=${GOOGLE_MAP_API_KEY}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    container_name: rumble-db
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  web-server:
    image: nginx:1.25.4
    container_name: nginx
    ports:
      - "80:80"
    environment:
      - APP_HOST=app
      - APP_PORT=8000
    volumes:
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - static-data:/app/staticfiles
      - media-data:/app/staticfiles
    depends_on:
      - app

volumes:
  db-data:
  static-data:
  media-data:
