# Generated by Django 4.1 on 2022-08-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=11)),
                ('country_code', models.CharField(choices=[('NG', '+234'), ('GH', '+233')], default='NG', max_length=15)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
