# Generated by Django 4.1 on 2022-09-06 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ratings', models.FloatField(default=0)),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('african', 'African'), ('alcoholic drinks', 'Alcoholic Drinks'), ('bakery and cakes', 'Bakery and Cakes'), ('breakfast', 'Breakfast'), ('chinese', 'Chinese'), ('fast food', 'Fast Food'), ('grills', 'Grills'), ('ice cream', 'Ice Cream'), ('pizza', 'Pizza'), ('vegan', 'Vegan')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpenHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('weekday', models.IntegerField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.vendor')),
            ],
        ),
    ]
