# Generated by Django 4.1 on 2022-09-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_vendor_max_delivery_time_vendor_min_devivery_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='min_devivery_time',
            new_name='min_delivery_time',
        ),
    ]
