# Generated by Django 4.1 on 2022-09-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_vendor_openhours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenHours',
            new_name='OpenHour',
        ),
    ]
