# Generated by Django 4.1 on 2022-09-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
