# Generated by Django 4.1 on 2022-09-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_rename_min_devivery_time_vendor_min_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
