# Generated by Django 4.1 on 2022-09-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_product_image_alter_vendor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
