# Generated by Django 4.1 on 2022-09-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_vendor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(default='static/images/anonymous-avatar.png', null=True, upload_to=''),
        ),
    ]
