# Generated by Django 4.1 on 2022-10-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_shippingaddressorder_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='db_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
