# Generated by Django 4.1 on 2022-10-30 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_shippingaddress_db_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddressorder',
            name='zip_code',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
