# Generated by Django 4.1 on 2022-11-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_alter_shippingaddressorder_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='db_id',
        ),
    ]
