# Generated by Django 4.1 on 2022-11-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_alter_vendor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='state',
        ),
    ]
