# Generated by Django 4.1 on 2022-12-09 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_alter_vendor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='ratings',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
